name: 'ibm_hr_dbt'
version: '1.0.0'
config-version: 2

profile: 'ibm_hr_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Quote mixed-case PostgreSQL identifiers
quoting:
  database: false
  schema: false
  identifier: true

models:
  ibm_hr_dbt:

    # Staging layer
    staging:
      +materialized: view

    # Business-ready models
    marts:
      +materialized: table